# Generated by Django 3.1.2 on 2020-10-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Awwardstars', '0003_projects_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='reviews',
            field=models.IntegerField(default=0),
        ),
    ]
