# Generated by Django 3.1.2 on 2020-10-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Awwardstars', '0004_projects_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
